print("Hello".rjust(10))
print("Hello".rjust(20))
print("Hello World".rjust(20))
print("Hello".ljust(10))
print("Hello".rjust(20, "*"))
print("Hello".ljust(20, '-'))
print("Hello".center(20))
print("Hello".center(20, "="))